/**
 * Font pipeline — downloads the woff2 files we actually use into
 * `public/fonts/` and writes `src/styles/fonts.css` pointing at them.
 *
 *   npm run fonts
 *
 * The Classical stylesheet ships an `@import` from fonts.googleapis.com. That
 * is render-blocking on a cold cache and puts a third-party request on the
 * critical path, which fights the "loads quickly" requirement — so the faces
 * are self-hosted instead. Only the subsets the site can actually display are
 * fetched: latin and latin-ext, which cover both the English and German copy.
 *
 * Output is committed, so a fresh clone runs without network access.
 */
import { mkdir, writeFile, rm } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const FONT_DIR = path.join(root, 'public', 'fonts')
const CSS_OUT = path.join(root, 'src', 'styles', 'fonts.css')

// A modern desktop UA is required or Google serves the legacy ttf payload.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const FAMILIES = [
  {
    name: 'Cormorant Garamond',
    query: 'Cormorant+Garamond:ital,wght@0,400;0,600;1,400',
    subsets: ['latin', 'latin-ext'],
  },
  {
    name: 'Lora',
    query: 'Lora:ital,wght@0,400;0,600;1,400',
    subsets: ['latin', 'latin-ext'],
  },
  // Latin-only, bold weight: the wordmark borrows this cut for the logo in
  // every locale (see .nav-bar__brand-name), so "Woofles" needs Latin glyphs
  // from this family even though body/heading copy never does.
  { name: 'Noto Serif Georgian', query: 'Noto+Serif+Georgian:wght@600', subsets: ['latin'] },
]

/** Split a Google Fonts stylesheet into blocks tagged with their subset comment. */
function parseFaces(css) {
  const faces = []
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g
  let m
  while ((m = re.exec(css))) {
    const [, subset, body] = m
    const pick = (prop) => body.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1].trim()
    const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
    if (!url) continue
    faces.push({
      subset,
      url,
      family: pick('font-family')?.replace(/['"]/g, ''),
      style: pick('font-style') ?? 'normal',
      weight: pick('font-weight') ?? '400',
      unicodeRange: pick('unicode-range'),
    })
  }
  return faces
}

async function main() {
  await rm(FONT_DIR, { recursive: true, force: true })
  await mkdir(FONT_DIR, { recursive: true })

  const blocks = []

  for (const family of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`
    const res = await fetch(url, { headers: { 'User-Agent': UA } })
    if (!res.ok) throw new Error(`${family.name}: ${res.status} ${res.statusText}`)

    const faces = parseFaces(await res.text()).filter((f) =>
      family.subsets.includes(f.subset),
    )
    if (!faces.length) throw new Error(`${family.name}: no matching subsets found`)

    for (const face of faces) {
      const slug = [
        family.name.toLowerCase().replace(/\s+/g, '-'),
        face.weight,
        face.style === 'italic' ? 'italic' : null,
        face.subset,
      ]
        .filter(Boolean)
        .join('-')
      const file = `${slug}.woff2`

      const bin = await fetch(face.url, { headers: { 'User-Agent': UA } })
      if (!bin.ok) throw new Error(`${file}: ${bin.status}`)
      await writeFile(path.join(FONT_DIR, file), Buffer.from(await bin.arrayBuffer()))

      blocks.push(
        [
          '@font-face {',
          `  font-family: '${face.family}';`,
          `  font-style: ${face.style};`,
          `  font-weight: ${face.weight};`,
          '  font-display: swap;',
          `  src: url('/fonts/${file}') format('woff2');`,
          face.unicodeRange ? `  unicode-range: ${face.unicodeRange};` : null,
          '}',
        ]
          .filter(Boolean)
          .join('\n'),
      )
      console.log(`${file}`)
    }
  }

  const header = [
    '/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.',
    ' * Run `npm run fonts` to refresh. Faces are self-hosted from /public/fonts',
    ' * so no third-party request sits on the critical rendering path.',
    ' */',
    '',
  ].join('\n')

  await writeFile(CSS_OUT, header + blocks.join('\n\n') + '\n')
  console.log(`\n${blocks.length} faces -> src/styles/fonts.css`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
